server:
  port: 8088

broker:
  provider: scorpio
  external-url:
    scheme: "https"
    domain: "your-app-domain"
    port: 443
  internal-url:
    scheme: "https"
    domain: "your-app-domain"
    port: 443
  paths:
    entities: "/ngsi-ld/v1/entities"

app:
  config-source:
    name: azure

vault:
  provider:
    name: azure

azure:
  app:
    endpoint: ${APP_CONFIG_ENDPOINT}
    label:
      global: service-discovery
  key-vault:
    endpoint: "your-endpoint"

auth-server:
  external-url:
    scheme: "https"
    domain: "your-app-domain"
    port: 443
    path: "your-path"
  internal-url:
    scheme: "https"
    domain: "your-app-domain"
    port: 443
    path: "your-path"
  token-url:
    scheme: "https"
    domain: "your-app-domain"
    port: 443
    path: "your-path"

verifiable-presentation:
  expiration-time: 3
  expiration-unit: MINUTES

wallet-wda:
  urls:
    - scheme: https
      domain: "your-wda-domain"
      port: 443
    - scheme: http
      domain: localhost
      port: 4200
